django/helloworld/helloworld/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include

urlpatterns = [
    url(r'^music/', include('music.urls') ),
    url('admin/', admin.site.urls),
]

django/helloworld/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    #url(r'^$', views.index, name= 'index'),
    url(r'^$', views.IndexView.as_view(), name= 'index'),

    #/music/712
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name= 'detail'),

    #/music/album/add/
    url(r'album/add/$', views.AlbumCreate.as_view(), name= 'album-add'),

    #/music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name= 'album-update'),

    #/music/album/2/delete/
    #url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name= 'album-delete'),
]

django/helloworld/music/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Album( models.Model ):
    artist = models.CharField(max_length=250)
    album_title = models.CharField( max_length = 500 )
    genre = models.CharField( max_length = 100 )
    album_logo = models.CharField( max_length= 1000 )

    def __str__(self):
        return self.album_title + '_' + self.artist

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

class Song( models.Model ):
    album = models.ForeignKey( Album, on_delete= models.CASCADE )
    file_type = models.CharField( max_length= 10 )
    song_title = models.CharField( max_length= 250 )
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

django/helloworld/pools/models.py
from django.db import models

# Create your models here.

django/helloworld/music/views.py
#from django.http import HttpResponse
#from django.http import Http404
#from django.shortcuts import render, get_object_or_404
#from .models import Album, Song
##from django.template import loader
#
## Create your views here.
#def index(request):
#    all_albums = Album.objects.all()
#    '''
#    html = ''
#    for album in all_albums:
#        url = '/music/' + str(album.id) + '/'
#        html += '<a href="' + url + '">' + album.album_title + '</a><br>'
#    #print( "html: " + html )
#    return HttpResponse(html)
#    '''
#    '''
#    template = loader.get_template( 'music/index.html' )
#    context = {
#        'all_albums' : all_albums,
#    }
#    return HttpResponse(template.render( context, request) )
#    '''
#    context = {
#        'all_albums' : all_albums,
#    }
#    return render(request, 'music/index.html', context)
#
#def detail(request, album_id):
#    #return HttpResponse("<h2>Details for  album id: " + str(album_id) + "</h2>")
#    '''
#    all_albums = Album.objects.all()
#    template = loader.get_template( 'music/detail.html' )
#    context = {
#        'album' : all_albums[int(album_id)-1],
#    }
#    return HttpResponse(template.render( context, request) )
#    '''
#    '''
#    try:
#        album = Album.objects.get(pk=album_id)
#    except Album.DoesNotExist:
#        raise Http404("Album does not exist")
#    '''
#    album = get_object_or_404(Album, pk=album_id)
#    return render(request, 'music/detail.html', { 'album': album })
#
#def favorite(request, album_id):
#    album = get_object_or_404(Album, pk=album_id)
#    try:
#        selected_song = album.song_set.get(pk=request.POST['song'])
#    except (KeyError, Song.DoesNotExist):
#        return render(request, 'music/detail.html', {
#            'album': album,
#            'error_message' : 'You did not select a valid song'
#            } )
#    else:
#        selected_song.is_favorite = True
#        selected_song.save()
#        return render(request, 'music/detail.html', { 'album': album })


from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    sucess_url = reverse_lazy( 'music:index' )

django/helloworld/pools/views.py
from django.shortcuts import render

# Create your views here.

django/helloworld/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}
Add a New Album
{% endblock %}

{% block body %}

<div class='container-fluid'>
    <div class='row'>

        <div class='col-sm-12 col-md-7'>
            <div class='panel panel-default'>
                <div class='panel panel-body'>

                    <form class='form-horizontal' action='' method='post' enctype='mulipoart/form-data'>
                        {% csrf_token %}

                        {% include 'music/form-template.html' %}
                        <div class='form-group'>
                            <div class='col-sm-offset-2 col-sm-10'>
                                <button type='submit' class='btn btn-sucess'>
                                    Submit
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>
</div>

{% endblock %}

django/helloworld/music/templates/music/base.html
<!DOCTYPE html>
<html lang='en'>

    <head>
        <meta charset='UTF-8'>
            {% load staticfiles %}
            <link rel='stylesheet' type='text/css' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css' >
            <link rel='stylesheet' type='text/css' href='{% static 'music/style.css' %}'>
            <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Satisfy' >
            <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js'></script>
            <script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js'></script>
            <title>{% block title %}Henry{% endblock %}</title>
    </head>

    <body>
        <nav class='navbar navbar-inverse'>
            <div class='container-fluid'>
                <!-- Logo -->
                <div class='navbar-header'>
                    <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavBar'>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                        <span class='icon-bar'></span>
                    </button>
                    <a class='navbar-brand' href='{% url 'music:index' %}'>Henry</a>
                </div>
        
                <!-- Items -->
                <div class='collapse navbar-collapse' id='topNavBar'>
        
                    <ul class='nav navbar-nav'>
                        <li class=''>
                            <a href='{% url 'music:index' %}'>
                                <span class='glyphicon glyphicon-cd' aria-hidden='true'></span>&nbsp;
                                Albums
                            </a>
                        </li>
        
                        <li class=''>
                            <a href='{% url 'music:index' %}'>
                                <span class='glyphicon glyphicon-music' aria-hidden='true'></span>&nbsp;
                                Songs 
                            </a>
                        </li>
        
                    </ul>
        
                    <!-- -->
                    <form class='navbar-form navbar-left' role='search' method='get' action'#'>
                        <div class='form-group'>
                            <input type='text' class='form-control' name='q' value=''>
                        </div>
                        <button type='submit' class='btn btn-default'>
                            Search
                        </button>
                    </form>
                    <!-- -->
                    <ul class='nav navbar-nav navbar-right'>
        
                        <li class=''>
                            <a href='{% url 'music:album-add' %}'>
                                <span class='glyphicon glyphicon-plus' aria-hidden='true'></span>&nbsp;
                                Add Album
                            </a>
                        </li>
        
                        <li class=''>
                            <a href='{% url 'music:index' %}'>
                                <span class='glyphicon glyphicon-off' aria-hidden='true'></span>&nbsp;
                                Logout
                            </a>
                        </li>
        
                    </ul>
                </div>
        
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>

</html>

django/helloworld/music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block body %}
    <img src="{{ album.album_logo }}" style='width: 250px;'>
    
    <h1>{{ album.album_title }}</h1>
    <h3>{{ album.artist }}</h3>
    
    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% for song in album.song_set.all %}
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
            <img src='https://i.imgur.com/b9b13Rd.png'>
            {% endif %}
        </label><br>
    {% endfor %}

{% endblock %}

django/helloworld/music/templates/music/form-template.html
{% for field in form %}
    <div class='form-group'>
        <div class='col-sm-offset-2 col-sm-10'>
            <span class='text-danger small'>{{ field.errors }}</span>
        </div>

        <label class='control-label col-sm-2'>
            {{ field.label_tag }}
        </label>

        <div class='col-sm-10'>
            {{ field }}
        </div>
    </div>
{% endfor %}

django/helloworld/music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}
    {% if all_albums %}
         <h3>Here are all my albums</h3>
         <ul>
             {% for album in all_albums %}
             <!-- <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li> -->
                 <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

             {% endfor %}
         </ul>
    {% else %}
        <h3>You don't have any album</h3>
    {% endif %}
{% endblock %}